import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { dbConnect } from "@/service/mongo";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const poppins = Inter({ subsets: ["latin"], variable: "--font-poppins" });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const conn = await dbConnect();
  return (
    <html lang="en">
      <body className={cn(inter.variable, poppins.variable)}>
        {children}
      </body>
    </html>
  );
}
